[[nav]]
identifier = "About"
name = "iabout"
url = "#about"
weight = 1
[[nav]]
identifier = "contact"
name = "tlp"
url = "#contact"
weight = 2
[[nav]]
identifier = "download cv"
name = "idownload"
url = "#"
weight = 3
[[nav]]
identifier = "portfolio"
name = "ifile"
url = "#portfolio"
weight = 4
[[nav]]
identifier = "project"
name = "ifile"
url = "#project"
weight = 5
[[nav]]
identifier = "blog"
name = "inote"
url = "/blog"
weight = 6
[[nav]]
identifier = "Catatan"
name = "inote"
url = "/note"
weight = 7

# sosmed muryp -----------------------------
[[sosmed]]
identifier = "fb"
name = "@alifprihantoro"
url = "facebook.com/alifprihantoro"
weight = 1
[[sosmed]]
identifier = "ig"
name = "@alifprihantoro"
url = "instagram.com/alifprihantoro"
weight = 2
[[sosmed]]
identifier = "tw"
name = "@alifprihantoro"
url = "twitter.com/alifprihantoro"
weight = 3
