seturl = "https://muryp.my.id/"
title = "MuryP Beta"
theme = "muryp-now"
disqusShortname = "muryp"

[outputs]
    home = ["HTML", "RSS", "JSON"]
    pages = ["HTML", "RSS", "JSON"]
    page = ["HTML", "RSS", "JSON"]
    section = ["HTML", "RSS", "JSON"]

[taxonomies]
  tags = "tags"
  tags2 = "tags2"
  # author = "authors"

[permalinks]
  blog = "/blog/:slug/"
  note = "/note/:slug/"
  laman = "/pages/:slug/"
  # en = "/en/:slug/"

[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "box"

# Default JPEG or WebP quality setting. Default is 75.
quality = 75

# Default hint about what type of image. Currently only used for WebP encoding.
# Default is "photo".
# Valid values are "picture", "photo", "drawing", "icon", or "text".
hint = "photo"

# Anchor used when cropping pictures.
# Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
# Smart Cropping is content aware and tries to find the best crop for each image.
# Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
anchor = "smart"

# Default background color.
# Hugo will preserve transparency for target formats that supports it,
# but will fall back to this color for JPEG.
# Expects a standard HEX color string with 3 or 6 digits.
# See https://www.google.com/search?q=color+picker
bgColor = "#ffffff"

[imaging.exif]
 # Regexp matching the fields you want to Exclude from the (massive) set of Exif info
# available. As we cache this info to disk, this is for performance and
# disk space reasons more than anything.
# If you want it all, put ".*" in this config setting.
# Note that if neither this or ExcludeFields is set, Hugo will return a small
# default set: GPS|Exif|Exposure[M|P|B]|Contrast|Resolution|Sharp|JPEG|Metering|Sensing|Saturation|ColorSpace|Flash|WhiteBalance
includeFields = ""

# Regexp matching the Exif fields you want to exclude. This may be easier to use
# than IncludeFields above, depending on what you want.
excludeFields = ""

# Hugo extracts the "photo taken" date/time into .Date by default.
# Set this to true to turn it off.
disableDate = false

# Hugo extracts the "photo taken where" (GPS latitude and longitude) into
# .Long and .Lat. Set this to true to turn it off.
disableLatLong = false

languageCode = "id-id"
DefaultContentLanguage = "id"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[markup]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'
languageCode = 'id-id'
[author]
  name = 'Alief Prihantoro'

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
[params]
header = "Ingin Membuat Website?<br>Tapi tidak bisa coding. Tenang, serahkan projek anda kepada saya."
github = "https://github.com/alifprihantoro"
gitlab = "https://gitlab.com/alifprihantoro"
facebook = "https://facebook.com/alifprihantoro"
sitename = "MuryP Beta"
twitter = "@alifprihantoro"
og_image = "https://alifprihantoro.gitlab.io/image/noimg.png"
hosting = "/script/"
host = "/img/"
img = "/authors/muryp.png"
thumb = "/authors/muryp.min.png"
icon = "/image/muryp/favicon.ico"
bagianAtas = "https://alifprihantoro.gitlab.io/image/bg.png"
# Site Author
author = "MuryP"
# Description/subtitle for homepage
description = "MuryP, MuryP Beta, Internet, Technology, hardware, Operating Sistem, Software, Jaringan Komunikasi, JarKom, TIK, Ringkasan, Alief Prihantoro, Alif MuryP, Buku, Ebook,My Project Drawing/Desain,UI/UX,front end,Blogging, SEO,catatan"

pygmentsUseClasses=true
[[menu.ask]]
identifier = "@alifprihantoro"
name = "twitter"
url = "https://twitter.com/alifprihantoro"
weight = 1
[[menu.ask]]
identifier = "Muryp Beta"
name = "facebook"
url = "https://facebook.com/alifprihantoro"
weight = 2
[[menu.contact]]
identifier = "@muryp"
name = "telegram"
url = "https://t.me/muryp"
weight = 1
[[menu.contact]]
identifier = "alifprihantoro@gmail.com"
name = "gmail"
url = "mailto:alifprihantoro@gmail.com"
weight = 2
[[menu.contact]]
identifier = "+6283 829 383 123"
name = "tlp"
url = "https://wa.me/message/PE5QUV4RBIU6L1"
weight = 3
[[main]]
identifier = "Home"
name = "Home"
url = "/"
weight = 1
[[main]]
identifier = "About"
name = "About"
url = "/about/"
weight = 2
[[main]]
identifier = "Kontak"
name = "Kontak"
url = "/contact/"
weight = 3
[[main]]
identifier = "Catatan"
name = "Catatan"
url = "/note/"
weight = 4
[[main]]
identifier = "Bookmark"
name = "Bookmark"
url = "/bookmark"
weight = 5
[[main]]
identifier = "Kumpulan Ide"
name = "Kumpulan Ide"
url = "/ideku/"
weight = 6
[[menu.sosmed]]
identifier = "github"
name = "github"
url = "https://github.com/alifprihantoro"
weight = 1
[[menu.sosmed]]
identifier = "linkedin"
name = "linkedin"
url = "https://www.linkedin.com/in/alifprihantoro"
weight = 2
[[menu.sosmed]]
identifier = "instagram"
name = "instagram"
url = "https://www.instagram.com/murypstudio/"
weight = 3
[[menu.sosmed]]
identifier = "twitter"
name = "twitter"
url = "https://twitter.com/murypstudio"
weight = 4
[[menu.sosmed]]
identifier = "facebook"
name = "facebook"
url = "https://facebook.com/murypstudio"
weight = 5
[[menu.sosmed]]
identifier = "pinteres"
name = "pinteres"
url = "https://pinterest.com/alifprihantoro/"
weight = 6
[[menu.top]]
identifier = "Contact Me"
name = "tlp"
url = "https://wa.me/message/PE5QUV4RBIU6L1"
weight = 1
[[menu.top]]
identifier = "Download CV"
name = "dl"
url = "/link"
weight = 2
