[[menu.ask]]
identifier = "@alifprihantoro"
name = "twitter"
url = "https://twitter.com/alifprihantoro"
weight = 1
[[menu.ask]]
identifier = "Muryp Beta"
name = "facebook"
url = "https://facebook.com/alifprihantoro"
weight = 2
